FROM apache/airflow:3.1.7-python3.12

WORKDIR /opt/airflow/

USER root

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /opt/airflow/requirements.txt

USER airflow

RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt